#!/usr/bin/env python3
"""Wandelt eine BDF-Pixelschrift in eine C-Tabelle für die Meloni-Engine (engine/meloni/font*.c).

    python3 tools/bdf2c.py spleen-8x16.bdf mel_font8x16 > engine/meloni/font8x16.c

Erzeugt `const uint16_t NAME[256][H]`: Latin-1 (0x20–0xFF), eine Zeile je uint16, linkes Pixel = Bit 15.
Fehlende Zeichen werden zu '?'. Die Zelle hat die Größe der FONTBOUNDINGBOX, Grundlinie wie in der Schrift.
"""
import sys


def parse(path):
    fbb = None
    glyphs = {}
    cp = bbx = rows = None
    with open(path, encoding="latin-1") as f:
        for line in f:
            parts = line.split()
            if not parts:
                continue
            key = parts[0]
            if key == "FONTBOUNDINGBOX":
                fbb = tuple(int(v) for v in parts[1:5])
            elif key == "ENCODING":
                cp = int(parts[1])
            elif key == "BBX":
                bbx = tuple(int(v) for v in parts[1:5])
            elif key == "BITMAP":
                rows = []
            elif key == "ENDCHAR":
                if cp is not None and 0 <= cp < 256:
                    glyphs[cp] = (bbx, rows)
                cp = bbx = rows = None
            elif rows is not None:
                rows.append(int(key, 16) << (4 * (4 - len(key))))   # auf 16 Bit links ausrichten
    return fbb, glyphs


def cell(fbb, glyph):
    fw, fh, fx, fy = fbb
    (w, h, x, y), rows = glyph
    out = [0] * fh
    top = (fh + fy) - (h + y)                 # Abstand der Glyphe von oben in der Zelle
    for i, r in enumerate(rows):
        row = top + i
        if 0 <= row < fh:
            out[row] = (r >> (x - fx)) & 0xFFFF if x >= fx else (r << (fx - x)) & 0xFFFF
    return out


def main():
    path, name = sys.argv[1], sys.argv[2]
    fbb, glyphs = parse(path)
    fw, fh = fbb[0], fbb[1]
    if fw > 16:
        sys.exit("höchstens 16 Pixel breit")
    print("// %dx%d Latin-1 font for Meloni, generated by tools/bdf2c.py from %s." % (fw, fh, path.split("/")[-1]))
    print("// Spleen by Frederic Cambus, BSD-2-Clause: https://github.com/fcambus/spleen (see engine/meloni/FONTS.md).")
    print("// Row-major, one uint16 per row, bit 15 = left pixel.")
    print("#include <stdint.h>")
    print()
    print("const uint16_t %s[256][%d] = {" % (name, fh))
    for cp in range(0x20, 0x100):
        g = glyphs.get(cp) or glyphs[ord("?")]
        rows = cell(fbb, g)
        label = chr(cp) if (0x20 < cp < 0x7F or cp > 0xA0) and cp != 0x5C else "U+%02X" % cp
        print("    [0x%02X] = {%s}, // %s" % (cp, ", ".join("0x%04X" % r for r in rows), label))
    print("};")


if __name__ == "__main__":
    main()
